
import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

const ProjectOutputPage: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { projectData, projectId } = location.state || {}; // Expecting projectData and projectId

  if (!projectData) {
    return (
      <div className="min-h-screen w-full bg-background text-foreground flex flex-col items-center justify-center p-4 sm:p-8 selection:bg-neon-green/50 selection:text-white">
        <Card className="w-full max-w-2xl bg-card shadow-xl shadow-neon-green/30 border border-neon-green/50">
          <CardHeader>
            <CardTitle className="text-2xl font-bold glowing-text text-center">
              Project Output
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-center text-muted-foreground">
              No project data found. Please submit the questionnaire first.
            </p>
          </CardContent>
          <CardFooter className="flex justify-center">
            <Button
              variant="outline"
              onClick={() => navigate('/')}
              className="border-neon-green text-neon-green hover:bg-neon-green/10"
            >
              <ArrowLeft className="mr-2 h-4 w-4" /> Back to Questionnaire
            </Button>
          </CardFooter>
        </Card>
      </div>
    );
  }

  const imageUrl = `https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80`;


  return (
    <div className="min-h-screen w-full bg-background text-foreground flex flex-col items-center p-4 sm:p-8 selection:bg-neon-green/50 selection:text-white">
      <header className="w-full max-w-4xl flex justify-between items-center mb-12 text-center">
        <Button
            variant="outline"
            onClick={() => navigate('/')}
            className="border-neon-green text-neon-green hover:bg-neon-green/10 absolute left-4 sm:left-8 top-4 sm:top-8"
          >
            <ArrowLeft className="mr-2 h-4 w-4" /> Back
          </Button>
        <div className="flex-grow text-center">
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight glowing-text mt-16 sm:mt-0">
            Submission Successful!
          </h1>
        </div>
      </header>
      <Card className="w-full max-w-2xl bg-card shadow-xl shadow-neon-green/30 border border-neon-green/50">
        <CardHeader>
          <CardTitle className="text-xl sm:text-2xl font-bold glowing-text text-center">
            Thank You!
          </CardTitle>
        </CardHeader>
        <CardContent className="text-center space-y-6">
          <img 
            src={imageUrl}
            alt="Laptop on a desk" 
            className="rounded-md mx-auto max-h-60 sm:max-h-80 object-cover shadow-lg border border-neon-green/30"
          />
          <p className="text-base sm:text-lg text-foreground/90">
            Your prompt (ID: <span className="font-semibold text-neon-green">{projectId || 'N/A'}</span>) is ready to copy from the Supabase Database.
          </p>
          <p className="text-sm sm:text-base text-muted-foreground">
            In n8n, you will find the output generated by the UI/UX designer agent once processed.
          </p>
           {/* Removed the pre block that showed JSON.stringify(projectData, null, 2) */}
        </CardContent>
         <CardFooter className="flex flex-col sm:flex-row justify-center sm:justify-end gap-4 pt-6">
            <Button
              onClick={() => navigate('/')}
              className="w-full sm:w-auto bg-neon-green text-primary-foreground hover:bg-neon-green-darker"
            >
              Start New Project
            </Button>
             {/* You can add a button to view project in Supabase if you have a direct link pattern */}
          </CardFooter>
      </Card>
      <footer className="mt-12 text-center text-sm text-muted-foreground">
        <p>&copy; {new Date().getFullYear()} Project Requirements Collector. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default ProjectOutputPage;

