
// This file is automatically generated. Do not edit it directly.
// MODIFIED: To use dynamic environment configuration
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getCurrentSupabaseConfig } from '@/config/environments';

const { supabaseUrl, supabaseAnonKey } = getCurrentSupabaseConfig();

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Supabase URL or Anon Key is missing. Ensure your environment configuration is set up correctly (e.g., src/config/env.development.ts).");
}
if (supabaseUrl.startsWith('YOUR_') || supabaseAnonKey.startsWith('YOUR_')) {
  console.warn(
    "Supabase client is using placeholder credentials. " +
    "Please update your environment-specific configuration files (e.g., src/config/env.development.ts) " +
    "with your actual Supabase project URLs and Anon Keys for each environment (dev, test, prod)."
  );
}


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage, // Use localStorage for session persistence
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true, // Important for OAuth redirects
  },
});
