// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebyzgsadxcxyzfffgeff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVieXpnc2FkeGN4eXpmZmZnZWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTU4MzcsImV4cCI6MjA2MzY3MTgzN30.yA88Y1uBh4IzMaW1HcpKw9shxyUXY_Qin45oEcOXhcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);