// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://desgwelmvfuktvpfkdnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlc2d3ZWxtdmZ1a3R2cGZrZG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODQzMTAsImV4cCI6MjA2Mzc2MDMxMH0.FAGek7EeZEniiiczgnRaYfX2dT4GosYlY6g6BN9yI9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);